apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - prod.yaml
    path: helm
    repoURL: https://gitlab.com/kube/nginx.git
    targetRevision: prod
  syncPolicy:
    automated:
      prune: true